### ISSUE TITLE
isahc requires http2 feature for http1 connections

### ISSUE THREAD

**Issue by dremon** [sagebind/isahc#130]
Reproduction:

```toml
[dependencies]
isahc = { version = "0.8", default-features = false, features = ["static-curl"] }
```

Attempting to perform any http call results in curl error "Unsupported protocol" unless http2 feature is added.
